db.url=jdbc:mysql://cloud3.googiehost.com:3306/piuqnwsm_estacionamiento?useSSL=true&requireSSL=true&verifyServerCertificate=false
db.usuario=piuqnwsm_estacionamiento
db.contrasena=eku2wCt53zKkzh7tk9Mn
correo.usuario=setsuna01001@gmail.com
correo.contrasena=tattqyyybglxyqtg
smtp.host=smtp.gmail.com
smtp.port=587
smtp.user=setsuna01001@gmail.com
smtp.pass=tattqyyybglxyqtg
smtp.tls=true
