<<<<<<< HEAD
db.url=jdbc:mysql://34.63.132.87:3306/estacionamiento?useSSL=true&requiereSSL=true&verifyServerCertificate=false
db.usuario=estacionamiento
db.contrasena=J@Q^l1SKvD:>7JzR
=======
db.url=jdbc:mysql://34.63.132.87:3306/estacionamiento?useSSL=true&requireSSL=true&verifyServerCertificate=false
db.usuario=estacionamiento
db.contrasena=J@Q^l1SKvD:>7JzR
correo.usuario=setsuna01001@gmail.com
correo.contrasena=tattqyyybglxyqtg
smtp.host=smtp.gmail.com
smtp.port=587
smtp.user=setsuna01001@gmail.com
smtp.pass=tattqyyybglxyqtg
smtp.tls=true
>>>>>>> ae0b63095fbe93b7e25bc1755f899c623dd6c5ca
