#Configuración actualizada por la UI
#Fri May 08 11:15:32 CST 2026
app.idioma=es_ES
app.nombre=Sistema de Estacionamiento
app.version=1.0.0
db.contrasena=eku2wCt53zKkzh7tk9Mn
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc\:mysql\://cloud3.googiehost.com\:3306/piuqnwsm_estacionamiento?useSSL\=true&requireSSL\=true&verifyServerCertificate\=false
db.usuario=piuqnwsm_estacionamiento
fecha.formato=dd/MM/yyyy
fecha_hora.formato=dd/MM/yyyy HH\:mm\:ss
pension.descuento.porcentaje=10.00
pension.duracion.minima=7
recordatorio.pension.dias=1
smtp.host=smtp.gmail.com
smtp.pass=tattqyyybglxyqtg
smtp.port=587
smtp.tls=true
smtp.user=setsuna01001@gmail.com
tarifa.auto.dia=25.00
tarifa.auto.hora=5.00
tarifa.auto.media=10.00
tarifa.camioneta.dia=35.00
tarifa.camioneta.hora=7.00
tarifa.camioneta.media=14.00
tarifa.moto.dia=15.00
tarifa.moto.hora=3.00
tarifa.moto.media=6.00
ui.idioma=es
ui.resolucion.alto=768
ui.resolucion.ancho=1024
ui.tema=default
