#Configuraci�n actualizada por la UI
#Thu May 07 10:46:47 CST 2026
app.idioma=es_ES
app.nombre=Sistema de Estacionamiento
app.version=1.0.0
db.contrasena=LiprElO3RH1>khaO
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc\:mysql\://23.251.145.208\:3306/estacionamiento_db
db.usuario=admin
fecha.formato=dd/MM/yyyy
fecha_hora.formato=dd/MM/yyyy HH\:mm\:ss
smtp.host=smtp.gmail.com
smtp.port=587
smtp.user=setsuna01001@gmail.com
smtp.pass=tattqyyybglxyqtg
smtp.tls=true
pension.descuento.porcentaje=10.00
pension.duracion.minima=7
recordatorio.pension.dias=3
tarifa.auto.dia=25.00
tarifa.auto.hora=5.00
tarifa.auto.media=10.00
tarifa.camioneta.dia=35.00
tarifa.camioneta.hora=7.00
tarifa.camioneta.media=14.00
tarifa.moto.dia=15.00
tarifa.moto.hora=3.00
tarifa.moto.media=6.00
ui.idioma=es
ui.resolucion.alto=768
ui.resolucion.ancho=1024
ui.tema=default
